export const INGREDIENTS_LOAD = `INGREDIENTS_LOAD`;
export const DATA_ERROR_DISPLAY_ON = 'DATA_ERROR_DISPLAY_ON';
export const DATA_ERROR_DISPLAY_OFF = 'DATA_ERROR_DISPLAY_OFF';

export const DATA_LOADING_ON = 'DATA_LOADING_ON';
export const DATA_LOADING_OFF = 'DATA_LOADING_OFF'