export const INGREDIENTS_LOAD = `INGREDIENTS_LOAD`;

export const INGREDIENTS_GET_SUCCESS = 'INGREDIENTS_GET_SUCCESS';

export const INGREDIENTS_GET_FAILED = 'INGREDIENTS_GET_FAILED';
export const DATA_ERROR_DISPLAY_ON = 'DATA_ERROR_DISPLAY_ON';
export const DATA_ERROR_DISPLAY_OFF = 'DATA_ERROR_DISPLAY_OFF';

export const DATA_LOADING_ON = 'DATA_LOADING_ON';
export const DATA_LOADING_OFF = 'DATA_LOADING_OFF';

export const MODAL_CLOSE = 'MODAL_CLOSE';
export const MODAL_OPEN = 'MODAL_OPEN';